spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaoan?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  freemarker:
      allow-request-override: false
      cache: false
      check-template-location: true
      charset: UTF-8
      suffix: .ftl
      templateLoaderPath: classpath:/templates/
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
